---
resources:
- name: artifactory-bosh-release-develop
  type: git
  source:
    uri: git@github.com:JFrogDev/artifactory-bosh-release.git 
    branch: master
    ignore_paths:
    - releases/cf-artifactory
    private_key: {{artifactory-bosh-release-private-key}}

- name: artifactory-bosh-release-master
  type: git
  source:
    uri: git@github.com:JFrogDev/artifactory-bosh-release.git 
    branch: master
    private_key: {{artifactory-bosh-release-private-key}}

- name: jfrog-artf-bosh-concourse-credentials
  type: git
  source:
    uri: git@github.com:JFrogDev/jfrog-artf-bosh-concourse-credentials.git 
    branch: master
    private_key: {{jfrog-artf-bosh-concourse-credentials-private-key}}

- name: version
  type: semver
  source:
    bucket: {{s3-artifacts-bucket}}
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: {{s3-region-name}}
    initial_version: 0.0.16

- name: final_bosh_release
  type: s3
  source:
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: {{s3-region-name}}
    bucket:  {{s3-final-release-bucket}}
    private: true
    regexp: artifactory-bosh-release-(.*).tgz

jobs:

- name: build-rc
  serial: true
  plan:
  - get: version
    params: {bump: patch, pre: rc}
  - put: version
    params: {file: version/number}
  - get: artifactory-bosh-release-develop
    trigger: true
  - get: artifactory-bosh-release-master
  - task: build-artifact
    file: artifactory-bosh-release-master/ci/build-artifact.yml
    config:
      params:
        BOSH_TARGET: {{bosh_ip}}
        BOSH_USERNAME: {{bosh_username}}
        BOSH_PASSWORD: {{bosh_password}}
        BOSH_MANIFEST: {{artifactory_manifest}}

- name: integration
  serial: true
  plan:
  - get: version
    passed: [build-rc]
  - get: artifactory-bosh-release-master
    passed: [build-rc]
    trigger: true
  - task: integration
    file: artifactory-bosh-release-master/ci/integration.yml
    config:
      params:
        BOSH_TARGET: {{bosh_ip}}
        BOSH_USERNAME: {{bosh_username}}
        BOSH_PASSWORD: {{bosh_password}}
        BOSH_MANIFEST: {{artifactory_manifest}}
        BOSH_DIRECTOR_SSH_USERNAME: {{bosh_director_ssh_username}}
        BOSH_DIRECTOR_SSH_PASSWORD: {{bosh_director_ssh_password}}


- name: shipit
  serial: true
  plan:
  - get: artifactory-bosh-release-master
    passed: [integration]
    trigger: true
  - get: jfrog-artf-bosh-concourse-credentials
  - get: version
    passed: [integration]
    params: {bump: final}
  - task: promote-to-final
    file: artifactory-bosh-release-master/ci/promote-to-final.yml
  - put: final_bosh_release 
    params: {from: artifactory-bosh-release-master/releases/cf-artifactory/cf-artifactory-.*.tgz}
  - put: version
    params: {file: version/number}
  - put: artifactory-bosh-release-master
    params:
      repository: promote-to-final/artifactory-bosh-release-master
      tag: version/number
      rebase: true
      tag_prefix: v
