---
resources:
- name: artifactory-bosh-release
  type: git
  source:
    uri: git@github.com:JFrogDev/artifactory-bosh-release.git 
    branch: master
    private_key: {{artifactory-bosh-release-private-key}}

- name: jfrog-artf-bosh-concourse-credentials
  type: git
  source:
    uri: git@github.com:JFrogDev/jfrog-artf-bosh-concourse-credentials.git 
    branch: master
    private_key: {{jfrog-artf-bosh-concourse-credentials-private-key}}

- name: version
  type: semver
  source:
    bucket: {{s3-artifacts-bucket}}
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: {{s3-region-name}}
    initial_version: 0.0.0

- name: rc_bosh_release
  type: s3
  source:
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: {{s3-region-name}}
    bucket:  {{s3-rc-release-bucket}}
    private: true
    regexp: artifactory-bosh-release-(.*).tgz

- name: final_bosh_release
  type: s3
  source:
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: {{s3-region-name}}
    bucket:  {{s3-final-release-bucket}}
    private: true
    regexp: artifactory-bosh-release-(.*).tgz

jobs:

- name: build-rc
  serial: true
  plan:
  - get: version
    params: {bump: patch, pre: rc}
  - put: version
    params: {file: version/number}
  - get: artifactory-bosh-release
    trigger: true
  - task: build-artifact
    file: artifactory-bosh-release/ci/build-artifact.yml
  - put: rc_bosh_release
    params: {from: artifactory-bosh-release/dev_releases/cf-artifactory/cf-artifactory-.*.tgz}

- name: integration
  serial: true
  plan:
  - get: version
    passed: [build-rc]
  - get: rc_bosh_release
    trigger: true
    passed: [build-rc]
  - get: artifactory-bosh-release
    passed: [build-rc]
  - task: integration
    file: artifactory-bosh-release/ci/integration.yml
    config:
      params:
        BOSH_LITE_IP: {{bosh_lite_ip}}

- name: shipit
  serial: true
  plan:
  - get: rc_bosh_release
    trigger: true
    passed: [integration]
  - get: artifactory-bosh-release
    passed: [integration]
  - get: jfrog-artf-bosh-concourse-credentials
  - get: version
    passed: [integration]
    params: {bump: final}
  - task: promote-to-final
    file: artifactory-bosh-release/ci/promote-to-final.yml
  - put: final_bosh_release 
    params: {from: artifactory-bosh-release/releases/cf-artifactory/cf-artifactory-.*.tgz}
  - put: version
    params: {file: version/number}
  - put: artifactory-bosh-release
    params:
      repository: promote-to-final/artifactory-bosh-release
      tag: version/number
      tag_prefix: v
