---
packages:
- name: common
  version: !binary |-
    ODBhMTMxM2E3OTAxMjEyNzMwMjBhM2Y3ZTQ1YzVkODQxNWM2ZDZhNQ==
  fingerprint: !binary |-
    ODBhMTMxM2E3OTAxMjEyNzMwMjBhM2Y3ZTQ1YzVkODQxNWM2ZDZhNQ==
  sha1: !binary |-
    YTM2NzQ0NWM2YzRjOTJmYjQ1NWNkNTY4ZGY5NmI0YjI1OTAwZDQ4NA==
  dependencies: []
- name: mysql-connector
  version: !binary |-
    YTUxMzU2NmNhMTE3ZTU1OWZmM2Q1ZWFhMzFkZmQ3MTc4MjkzNGFmMg==
  fingerprint: !binary |-
    YTUxMzU2NmNhMTE3ZTU1OWZmM2Q1ZWFhMzFkZmQ3MTc4MjkzNGFmMg==
  sha1: !binary |-
    OWIzZmFjYWVlZjUwZWJlZDNmNmIzZGZmOTNhNTkxY2FlNzViODE3ZA==
  dependencies: []
- name: artifactory
  version: !binary |-
    YjhmNzg3NTQzOTgxNWUxMDY0MGUzZjFiMGIzN2Q2NzViNzZiNDM3MA==
  fingerprint: !binary |-
    YjhmNzg3NTQzOTgxNWUxMDY0MGUzZjFiMGIzN2Q2NzViNzZiNDM3MA==
  sha1: !binary |-
    ODlkY2RjMWZjMDBhYjJlOWI1NTQzMTZiMzIzYzhkMTQzNmNhMGNjZQ==
  dependencies: []
- name: route-registrar
  version: !binary |-
    ZDQyNmJmNDg0ZTZjNGQ0ZmJlNmU4NzA4OTNkZjMyMTMwMjI4MzY1MQ==
  fingerprint: !binary |-
    ZDQyNmJmNDg0ZTZjNGQ0ZmJlNmU4NzA4OTNkZjMyMTMwMjI4MzY1MQ==
  sha1: !binary |-
    M2VmMGMyOWUzYjA4NzE5M2UxMDZiN2FhMGQwYjA5ZmVjZDZlOWE2NA==
  dependencies:
  - go
- name: jdk
  version: !binary |-
    ZmNlZTA3MzQ1NWZjMDY5ZmExMjVmNDhhZWIwYWMxZTc1YmQzZjBjOQ==
  fingerprint: !binary |-
    ZmNlZTA3MzQ1NWZjMDY5ZmExMjVmNDhhZWIwYWMxZTc1YmQzZjBjOQ==
  sha1: !binary |-
    YTU1YWFkODgyNGUxN2ZiYTNiNjYyODViZTgzNTdlZGFhNzEwMDFjMw==
  dependencies: []
- name: debian_nfs_server
  version: !binary |-
    Yjk2MzVjZWFmNDUyYjE2MjM5YjliNmEzNTZjZGM5ZDFjNmZhODBmNQ==
  fingerprint: !binary |-
    Yjk2MzVjZWFmNDUyYjE2MjM5YjliNmEzNTZjZGM5ZDFjNmZhODBmNQ==
  sha1: !binary |-
    Zjk2NjkzYzBmZjJmMmQ2MzBjNTdiNDhkYzVlODA3ZTg0MTJjYzk3ZA==
  dependencies: []
- name: go
  version: !binary |-
    MWM5MWZlYjU1YjcyZTkzNDBhNTJkYjk3NGY2ZDI5MjdiMmJlMjI1Yw==
  fingerprint: !binary |-
    MWM5MWZlYjU1YjcyZTkzNDBhNTJkYjk3NGY2ZDI5MjdiMmJlMjI1Yw==
  sha1: !binary |-
    NDA4YjQwYTQ5ZDQ0MjNmODI5NDQ5Y2VhM2ZiNTFkMjFkMWQ3YzZkZg==
  dependencies: []
jobs:
- name: standalone
  version: !binary |-
    YzY4MGRiYjg0ZTFmMGExN2NhYjBiNDg3ZjM5Y2U3NzAyMTNiNWFlYw==
  fingerprint: !binary |-
    YzY4MGRiYjg0ZTFmMGExN2NhYjBiNDg3ZjM5Y2U3NzAyMTNiNWFlYw==
  sha1: !binary |-
    ZmQxOWRlYzVkMDA1YjliODczZDZmN2MzMTIzODY3ZjFmY2IzYTMzNA==
- name: debian_nfs_server
  version: !binary |-
    Nzk4ZDE2ZGFkM2UzZDk4NTFlODhlN2VkNjU0MDMwYmIxMjg1MjdmYg==
  fingerprint: !binary |-
    Nzk4ZDE2ZGFkM2UzZDk4NTFlODhlN2VkNjU0MDMwYmIxMjg1MjdmYg==
  sha1: !binary |-
    Mjc4YTM4OGQyYWQ5M2I1NDFhZDZkMTM1MWViYjhjMTZiOTNlMjQ1MA==
commit_hash: 7a13f23c
uncommitted_changes: false
name: cf-artifactory
version: 0.3.17
