---
packages:
- name: common
  version: !binary |-
    ODBhMTMxM2E3OTAxMjEyNzMwMjBhM2Y3ZTQ1YzVkODQxNWM2ZDZhNQ==
  fingerprint: !binary |-
    ODBhMTMxM2E3OTAxMjEyNzMwMjBhM2Y3ZTQ1YzVkODQxNWM2ZDZhNQ==
  sha1: !binary |-
    ZjYzMTlmZGJlYTVjNTNjNGZmM2ZjZDBiMGM5YWI1ZmU3OTU2ZTNjMw==
  dependencies: []
- name: mysql-connector
  version: !binary |-
    YTUxMzU2NmNhMTE3ZTU1OWZmM2Q1ZWFhMzFkZmQ3MTc4MjkzNGFmMg==
  fingerprint: !binary |-
    YTUxMzU2NmNhMTE3ZTU1OWZmM2Q1ZWFhMzFkZmQ3MTc4MjkzNGFmMg==
  sha1: !binary |-
    ZDQzMTgzN2U1Y2IyODZlYjQ0OTZjZWM5N2MyN2M4MjBlMTUwYzA0Zg==
  dependencies: []
- name: artifactory
  version: !binary |-
    YjhmNzg3NTQzOTgxNWUxMDY0MGUzZjFiMGIzN2Q2NzViNzZiNDM3MA==
  fingerprint: !binary |-
    YjhmNzg3NTQzOTgxNWUxMDY0MGUzZjFiMGIzN2Q2NzViNzZiNDM3MA==
  sha1: !binary |-
    ZGMyYTUyOGZiZDZhMjBkODA2MWRhNTBlOGQwMmRlMjNkZGRhN2FjMw==
  dependencies: []
- name: route-registrar
  version: !binary |-
    ZDQyNmJmNDg0ZTZjNGQ0ZmJlNmU4NzA4OTNkZjMyMTMwMjI4MzY1MQ==
  fingerprint: !binary |-
    ZDQyNmJmNDg0ZTZjNGQ0ZmJlNmU4NzA4OTNkZjMyMTMwMjI4MzY1MQ==
  sha1: !binary |-
    ODZjYzNiNTAyZWRjM2Q4NjEwYTZkMzFiOTJlMzAwZjMzNzU4YzliMQ==
  dependencies:
  - go
- name: jdk
  version: !binary |-
    ZmNlZTA3MzQ1NWZjMDY5ZmExMjVmNDhhZWIwYWMxZTc1YmQzZjBjOQ==
  fingerprint: !binary |-
    ZmNlZTA3MzQ1NWZjMDY5ZmExMjVmNDhhZWIwYWMxZTc1YmQzZjBjOQ==
  sha1: !binary |-
    YTg0MTkwODRjNWVmYWQwNDcyZWI4YmExYjE5YTk5NmEyNGU3ZGJmZA==
  dependencies: []
- name: debian_nfs_server
  version: !binary |-
    Yjk2MzVjZWFmNDUyYjE2MjM5YjliNmEzNTZjZGM5ZDFjNmZhODBmNQ==
  fingerprint: !binary |-
    Yjk2MzVjZWFmNDUyYjE2MjM5YjliNmEzNTZjZGM5ZDFjNmZhODBmNQ==
  sha1: !binary |-
    NmJiYzA0NTZiMWU3MzIxZGJiNWExNWExMjgyMWJiN2VkMDM4OWZhMA==
  dependencies: []
- name: go
  version: !binary |-
    MWM5MWZlYjU1YjcyZTkzNDBhNTJkYjk3NGY2ZDI5MjdiMmJlMjI1Yw==
  fingerprint: !binary |-
    MWM5MWZlYjU1YjcyZTkzNDBhNTJkYjk3NGY2ZDI5MjdiMmJlMjI1Yw==
  sha1: !binary |-
    NDBhZWM1YTQwNmYzNTI0NzIxYTZlOTkyYTBiN2EzOTQ2NzgzOTI5OQ==
  dependencies: []
jobs:
- name: standalone
  version: !binary |-
    OTZkZmFkMjIyMzhmNDZjYmMzNmFhMjhiZDY4YzhmZDEwMjhmODIwYQ==
  fingerprint: !binary |-
    OTZkZmFkMjIyMzhmNDZjYmMzNmFhMjhiZDY4YzhmZDEwMjhmODIwYQ==
  sha1: !binary |-
    ZDZjZTBiMjljMjUyOTE4NDdmN2NjYmY5YTBkY2QzNTYyNGZlZDQwZQ==
- name: debian_nfs_server
  version: !binary |-
    NzRjYmVlZDYxOTI1YWM1NjBhODc2OTRiMjQxZmI2MjNiOGNkNzQ5Ng==
  fingerprint: !binary |-
    NzRjYmVlZDYxOTI1YWM1NjBhODc2OTRiMjQxZmI2MjNiOGNkNzQ5Ng==
  sha1: !binary |-
    ZmVhY2UwMzBhZjQzOTZhYmY3ODJiMDM0MDRkODliZDgxNDBhNzU0NQ==
commit_hash: 52fff379
uncommitted_changes: false
name: cf-artifactory
version: 0.3.11
