---
packages:
- name: jdk
  version: !binary |-
    ZmNlZTA3MzQ1NWZjMDY5ZmExMjVmNDhhZWIwYWMxZTc1YmQzZjBjOQ==
  fingerprint: !binary |-
    ZmNlZTA3MzQ1NWZjMDY5ZmExMjVmNDhhZWIwYWMxZTc1YmQzZjBjOQ==
  sha1: !binary |-
    Mjg3Mzk2OGJhYzMxY2ZmMWM4YjE5MTc0YWM1MGM0MTRjYTdkZWM4Nw==
  dependencies: []
- name: artifactory
  version: !binary |-
    YjhmNzg3NTQzOTgxNWUxMDY0MGUzZjFiMGIzN2Q2NzViNzZiNDM3MA==
  fingerprint: !binary |-
    YjhmNzg3NTQzOTgxNWUxMDY0MGUzZjFiMGIzN2Q2NzViNzZiNDM3MA==
  sha1: !binary |-
    MzM5Mzk0NDcxNGExYmFlM2RjM2JkYWMwNTcyZDhmMDZlMzE3NmUyMw==
  dependencies: []
jobs:
- name: standalone
  version: !binary |-
    N2FjY2ZkNzFiMWQ4ODgxZjBiOTlhZDI4M2YyZWQ1ODkzZGQwOGJjZA==
  fingerprint: !binary |-
    N2FjY2ZkNzFiMWQ4ODgxZjBiOTlhZDI4M2YyZWQ1ODkzZGQwOGJjZA==
  sha1: !binary |-
    NzlkYTYwNmMyMWM4Nzk0MGI3MGYwYTJmMGI2YTYyNThjNDUwNzU2Mg==
commit_hash: 26920bad
uncommitted_changes: false
name: cf-artifactory
version: 0.0.10
