---
packages:
- name: common
  version: !binary |-
    ODBhMTMxM2E3OTAxMjEyNzMwMjBhM2Y3ZTQ1YzVkODQxNWM2ZDZhNQ==
  fingerprint: !binary |-
    ODBhMTMxM2E3OTAxMjEyNzMwMjBhM2Y3ZTQ1YzVkODQxNWM2ZDZhNQ==
  sha1: !binary |-
    ODNlMWU5MjhlMzFjMDk3YTYxOTA0ODM4ODdmZWJlOGJmM2Q3ZDE5OQ==
  dependencies: []
- name: mysql-connector
  version: !binary |-
    YTUxMzU2NmNhMTE3ZTU1OWZmM2Q1ZWFhMzFkZmQ3MTc4MjkzNGFmMg==
  fingerprint: !binary |-
    YTUxMzU2NmNhMTE3ZTU1OWZmM2Q1ZWFhMzFkZmQ3MTc4MjkzNGFmMg==
  sha1: !binary |-
    ZjZjYTQ5NWQ2YjU3NWY4OWQzNzYwZTk4Y2ZhYjg0N2Y4ZTRkMTExYQ==
  dependencies: []
- name: artifactory
  version: !binary |-
    YjhmNzg3NTQzOTgxNWUxMDY0MGUzZjFiMGIzN2Q2NzViNzZiNDM3MA==
  fingerprint: !binary |-
    YjhmNzg3NTQzOTgxNWUxMDY0MGUzZjFiMGIzN2Q2NzViNzZiNDM3MA==
  sha1: !binary |-
    NzMxM2U4MTVhNGY3NDQ3MGUxOGRkN2ZjM2ZiZWFhZDIyZGRlMGEwNA==
  dependencies: []
- name: route-registrar
  version: !binary |-
    ZDQyNmJmNDg0ZTZjNGQ0ZmJlNmU4NzA4OTNkZjMyMTMwMjI4MzY1MQ==
  fingerprint: !binary |-
    ZDQyNmJmNDg0ZTZjNGQ0ZmJlNmU4NzA4OTNkZjMyMTMwMjI4MzY1MQ==
  sha1: !binary |-
    N2VjNDFjMGY4ZjZlMGY1MzU0ZWJkNTVkNWM1M2Y3ZGFjMDY5MGU4Zg==
  dependencies:
  - go
- name: jdk
  version: !binary |-
    ZmNlZTA3MzQ1NWZjMDY5ZmExMjVmNDhhZWIwYWMxZTc1YmQzZjBjOQ==
  fingerprint: !binary |-
    ZmNlZTA3MzQ1NWZjMDY5ZmExMjVmNDhhZWIwYWMxZTc1YmQzZjBjOQ==
  sha1: !binary |-
    MzBmOGU2OGE1OWI4NGI2ZjUxOGU3YmEwODI2ZjkxZmRjOWRhODY0Mw==
  dependencies: []
- name: debian_nfs_server
  version: !binary |-
    Yjk2MzVjZWFmNDUyYjE2MjM5YjliNmEzNTZjZGM5ZDFjNmZhODBmNQ==
  fingerprint: !binary |-
    Yjk2MzVjZWFmNDUyYjE2MjM5YjliNmEzNTZjZGM5ZDFjNmZhODBmNQ==
  sha1: !binary |-
    ZjRiNzc1YmI2NDQ1ZDdkMzYwODVjZmEwNTYxMzhjY2EyNDA3NjE4Nw==
  dependencies: []
- name: go
  version: !binary |-
    MWM5MWZlYjU1YjcyZTkzNDBhNTJkYjk3NGY2ZDI5MjdiMmJlMjI1Yw==
  fingerprint: !binary |-
    MWM5MWZlYjU1YjcyZTkzNDBhNTJkYjk3NGY2ZDI5MjdiMmJlMjI1Yw==
  sha1: !binary |-
    YjBiYTJmOGRkODU1NzFjYWZjMzk5MTUyNzE0MTcxZjIwMzk5Y2RiNw==
  dependencies: []
jobs:
- name: standalone
  version: !binary |-
    NmM3YThkNzcwNGNhOWIyNDM5NmM4MDFhMjI5ODA2ODZlNmYwZDEwZQ==
  fingerprint: !binary |-
    NmM3YThkNzcwNGNhOWIyNDM5NmM4MDFhMjI5ODA2ODZlNmYwZDEwZQ==
  sha1: !binary |-
    YmJkYTA4MjZmNzI3MTU1NThkZmU3MjVhZDZkYmViMjQ0OWVhZDNmMQ==
- name: debian_nfs_server
  version: !binary |-
    NzRjYmVlZDYxOTI1YWM1NjBhODc2OTRiMjQxZmI2MjNiOGNkNzQ5Ng==
  fingerprint: !binary |-
    NzRjYmVlZDYxOTI1YWM1NjBhODc2OTRiMjQxZmI2MjNiOGNkNzQ5Ng==
  sha1: !binary |-
    MzliMGI5NzIzM2Q0NmQ2YTQ3OWM1MTQxMDcxNGU2NGI3ZTcwZGQ5Mw==
commit_hash: 804513c9
uncommitted_changes: false
name: cf-artifactory
version: 0.3.12
