---
packages:
- name: artifactory
  version: !binary |-
    OTIwMzc3YzZhZjIyNDA0NTQ1YTYwM2E5ZjNmYWM1OTFiZjMxZjdiNg==
  fingerprint: !binary |-
    OTIwMzc3YzZhZjIyNDA0NTQ1YTYwM2E5ZjNmYWM1OTFiZjMxZjdiNg==
  sha1: !binary |-
    YmExZjFiMGMzMjFkYjZjODE3MzcyMTliZDk2NjkxZjNiMzc2MTc0Nw==
  dependencies: []
- name: common
  version: !binary |-
    ODBhMTMxM2E3OTAxMjEyNzMwMjBhM2Y3ZTQ1YzVkODQxNWM2ZDZhNQ==
  fingerprint: !binary |-
    ODBhMTMxM2E3OTAxMjEyNzMwMjBhM2Y3ZTQ1YzVkODQxNWM2ZDZhNQ==
  sha1: !binary |-
    ZWYyZWM1Y2RmNmU3OWNlNDMxMDIxMmJhZGJlYTlkOTFiYzcxNTljOA==
  dependencies: []
- name: debian_nfs_server
  version: !binary |-
    Yjk2MzVjZWFmNDUyYjE2MjM5YjliNmEzNTZjZGM5ZDFjNmZhODBmNQ==
  fingerprint: !binary |-
    Yjk2MzVjZWFmNDUyYjE2MjM5YjliNmEzNTZjZGM5ZDFjNmZhODBmNQ==
  sha1: !binary |-
    ZDdmNGExMjk3OTY3MjNkNmVjNjY3ZjNhYjA0MjhhNTRjYmZjMThlOQ==
  dependencies: []
- name: go
  version: !binary |-
    MWM5MWZlYjU1YjcyZTkzNDBhNTJkYjk3NGY2ZDI5MjdiMmJlMjI1Yw==
  fingerprint: !binary |-
    MWM5MWZlYjU1YjcyZTkzNDBhNTJkYjk3NGY2ZDI5MjdiMmJlMjI1Yw==
  sha1: !binary |-
    NDlkNDQxYTZlNjc4ZmFmNTdiNWM4NjEwZmExMzliYzhkNmQ1OTBiYw==
  dependencies: []
- name: jdk
  version: !binary |-
    OWI5YzI4ZjM2YWVmY2Q4NmQ2NTkzMjk0YmQ2ZjRmYjNiMzdmYmY1OA==
  fingerprint: !binary |-
    OWI5YzI4ZjM2YWVmY2Q4NmQ2NTkzMjk0YmQ2ZjRmYjNiMzdmYmY1OA==
  sha1: !binary |-
    ZWQwNzIzNTljYTFlN2QxNjM0YWExZjg2ZWU5ZmJiOWYwM2Q0NTFkMQ==
  dependencies: []
- name: mysql-connector
  version: !binary |-
    NDUxZDk2NWIyZTE5ZjIwZmZmMjFiZjc0MjRiODM2YjNkZTkxZDkyMw==
  fingerprint: !binary |-
    NDUxZDk2NWIyZTE5ZjIwZmZmMjFiZjc0MjRiODM2YjNkZTkxZDkyMw==
  sha1: !binary |-
    MzhjOWEyOWE3OTRmMGU3NjhiZDU0YTdjYzU3NjA5YzNjOTBkYWM3MA==
  dependencies: []
- name: nginx
  version: !binary |-
    ZGQxNWM4MjAyNzY3MWM3NGIxMDhjNTJiY2VjYjY0ZmNhZjljMGQzOA==
  fingerprint: !binary |-
    ZGQxNWM4MjAyNzY3MWM3NGIxMDhjNTJiY2VjYjY0ZmNhZjljMGQzOA==
  sha1: !binary |-
    MWNlZTk0NWEzMmUxZGRjYTRjMTMwOGVhMmNlMzkwMjVjNmRjOGQwOA==
  dependencies: []
- name: route-registrar
  version: !binary |-
    NDFmMzBkYzRkODhhZDkyZTVlYWYwOGQwMjEwZjBmZTgxMTAxMjFlMg==
  fingerprint: !binary |-
    NDFmMzBkYzRkODhhZDkyZTVlYWYwOGQwMjEwZjBmZTgxMTAxMjFlMg==
  sha1: !binary |-
    MDJlNzY0NmE0OGZhN2NlZDRlYjVlNDhmYjQwMGI5YjdiMTUzMmE1Yw==
  dependencies:
  - go
jobs:
- name: debian_nfs_server
  version: !binary |-
    NTJmZTYwNTk5ZWJlMTNiZTc4MzZkMzgzOWMwZTcwMTA2Y2VkNGNjMg==
  fingerprint: !binary |-
    NTJmZTYwNTk5ZWJlMTNiZTc4MzZkMzgzOWMwZTcwMTA2Y2VkNGNjMg==
  sha1: !binary |-
    MzE3NmU4MDMwMWNlZjYyOGExZDNlNGVhNjQ4NjQyODZkNTU1NDg0MA==
- name: ha-artifactory
  version: !binary |-
    NmFmMTUwNGRmNDQwYjZkMmM3MTM5ZTQxMDQ5ZjA2ODkxZThiMmQzMw==
  fingerprint: !binary |-
    NmFmMTUwNGRmNDQwYjZkMmM3MTM5ZTQxMDQ5ZjA2ODkxZThiMmQzMw==
  sha1: !binary |-
    YzczNTY1MDkwZWRkODU5ZTI2YTA0OWNhYWRjMjQ2ZjY4YmRlMTg1ZA==
- name: nginx
  version: !binary |-
    YTVlYmFkZTZiM2Q1YTUwYmUwNGU1YjM2YjU1MjRhNTdhZGFiNWRkYw==
  fingerprint: !binary |-
    YTVlYmFkZTZiM2Q1YTUwYmUwNGU1YjM2YjU1MjRhNTdhZGFiNWRkYw==
  sha1: !binary |-
    NmY3NDk5YzZkOWY5ZTFlYmRkMmMwMDRkOWQzODYyZTlhZWU0ZGQyOA==
- name: standalone
  version: !binary |-
    NzFmYzU1NDk1ZjVjYWM5NDRhZGRiZTA5ZWFmMTNiYTM3YzRlNDZlNw==
  fingerprint: !binary |-
    NzFmYzU1NDk1ZjVjYWM5NDRhZGRiZTA5ZWFmMTNiYTM3YzRlNDZlNw==
  sha1: !binary |-
    NGQ0NzFhNTE3NjRkYWU0NWI4MTc1YTY2Y2IyMzNlZThjMGZiYzg4Ng==
commit_hash: cf9afbe3
uncommitted_changes: false
name: cf-artifactory
version: 0.6.6
