---
name: cf-artifactory
director_uuid: <%= `bosh status --uuid` %>
releases:
- name: cf-artifactory
  version: latest
compilation:
  cloud_properties:
    name: random
    cpu: 2
    ram: 2_048
    disk: 10_000
  network: services1
  reuse_compilation_vms: true
  workers: 1
update:
  canaries: 1
  canary_watch_time: 10000-100000
  update_watch_time: 10000-100000
  max_in_flight: 6
  serial: false
networks:
- name: services1
  type: manual
  subnets:
  - range: 10.60.0.0/16
    gateway: 10.60.0.1
    dns: [10.60.0.10]
    cloud_properties: {name: 'VM Network'}
    reserved: [10.60.7.0 - 10.60.7.50, 10.60.6.0/24, 10.60.5.0/24, 10.60.4.0/24, 10.60.3.0/24, 10.60.2.0/24, 10.60.1.0/24, 10.60.0.2 - 10.60.0.255, 10.60.7.100 - 10.60.255.254]
    static:
    - 10.60.7.52
    - 10.60.7.54
    - 10.60.7.55
    - 10.60.7.56
resource_pools:
- name: vms
  network: services1
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    cpu: 2
    ram: 4_096
    disk: 20_000
jobs:
- name: nginx
  templates:
  - name: nginx 
    release: cf-artifactory
  instances: 1
  resource_pool: vms
  networks:
  - name: services1
  properties:
    artifactory_host: 10.60.7.51
    artifactory_ha_nodes:
    - 10.60.7.54
    - 10.60.7.52
    - 10.60.7.55
    artifactory_route_name: bosh-artifactory
    artifactory_docker_dev_route_name: bosh-artifactory-docker-dev
    artifactory_docker_prod_route_name: bosh-artifactory-docker-prod
    cf:
      domain: <%= `echo $CF_DOMAIN` %>
      nats:
        host: <%= `echo $NATS_HOST` %>
        port: <%= `echo $NATS_PORT` %>
        username: <%= `echo $NATS_USERNAME` %>
        password: <%= `echo $NATS_PASSWORD` %>


- name: nfs_server
  templates:
  - name: debian_nfs_server
    release: cf-artifactory
  instances: 1
  resource_pool: vms
  persistent_disk: 8096
  networks:
  - name: services1
    static_ips:
    - 10.60.7.56
  properties:
    nfs_server:
      allow_from_entries:
      - 10.60.7.54
      - 10.60.7.52
      - 10.60.7.55
      no_root_squash: true

- name: ha-artifactory 
  templates:
  - name: ha-artifactory
    release: cf-artifactory
  instances: 3
  resource_pool: vms
  networks:
  - name: services1
    static_ips:
    - 10.60.7.54
    - 10.60.7.52
    - 10.60.7.55
  properties:
    artifactory_license_keys:
    - <%= `echo $ARTIFACTORY_LICENSE` %>
    - <%= `echo $ARTIFACTORY1_LICENSE` %>
    - <%= `echo $ARTIFACTORY2_LICENSE` %>
    artifactory_cluster_security_token: jdzddf584148ddzd185ddr1
    artifactory_ha_nodes:
    - 10.60.7.54
    - 10.60.7.52
    - 10.60.7.55
    artifactory_primary_node: 10.60.7.54
    database:
      host: <%= `echo $ARTIFACTORY_DB_HOST` %>
      port: <%= `echo $ARTIFACTORY_DB_PORT` %>
      name: <%= `echo $ARTIFACTORY_DB_NAME` %>
      username: <%= `echo $ARTIFACTORY_DB_USERNAME` %>
      password: <%= `echo $ARTIFACTORY_DB_PASSWORD` %>
    nfs:
      server_ip: 10.60.7.56
    binarystore:
      identity: <%= `echo $BINARYSTORE_IDENTITY` %>
      credential: <%= `echo $BINARYSTORE_CREDENTIAL` %>
