---
name: cf-artifactory
director_uuid: <%= `bosh status --uuid` %>
releases:
- name: cf-artifactory
  version: latest
compilation:
  cloud_properties:
    name: random
    cpu: 2
    ram: 2_048
    disk: 10_000
  network: services1
  reuse_compilation_vms: true
  workers: 1
update:
  canaries: 1
  canary_watch_time: 10000-100000
  update_watch_time: 10000-100000
  max_in_flight: 6
networks:
- name: services1
  type: manual
  subnets:
  - range: 10.60.0.0/16
    gateway: 10.60.0.1
    dns: [10.60.0.10]
    cloud_properties: {name: 'VM Network'}
    reserved:
    - 10.60.4.33
    - 10.60.4.37
    - 10.60.4.53
    static:
    - 10.60.4.54
    - 10.60.4.56
    - 10.60.4.58
resource_pools:
- name: vms
  network: services1
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    cpu: 2
    ram: 4_096
    disk: 20_000
jobs:
- name: nginx
  templates:
  - name: nginx 
    release: cf-artifactory
  instances: 1
  resource_pool: vms
  persistent_disk: 2048
  networks:
  - name: services1
    static_ips:
    - 10.60.4.58
  properties:
    artifactory_host: 10.60.4.54
    artifactory_route_name: bosh-artifactory
    cf:
      domain: <%= `echo $CF_DOMAIN` %>
      nats:
        host: <%= `echo $NATS_HOST` %>
        port: <%= `echo $NATS_PORT` %>
        username: <%= `echo $NATS_USERNAME` %>
        password: <%= `echo $NATS_PASSWORD` %>


- name: nfs_server
  templates:
  - name: debian_nfs_server
    release: cf-artifactory
  instances: 1
  resource_pool: vms
  persistent_disk: 8096
  networks:
  - name: services1
    static_ips:
    - 10.60.4.56
  properties:
    nfs_server:
      allow_from_entries:
      - 10.60.4.54
      no_root_squash: true

- name: standalone
  templates:
  - name: standalone
    release: cf-artifactory
  instances: 1
  resource_pool: vms
  networks:
  - name: services1
    static_ips:
    - 10.60.4.54
  properties:
    artifactory_license_key: <%= `echo $ARTIFACTORY_LICENSE` %>
    database:
      host: <%= `echo $ARTIFACTORY_DB_HOST` %>
      port: <%= `echo $ARTIFACTORY_DB_PORT` %>
      name: <%= `echo $ARTIFACTORY_DB_NAME` %>
      username: <%= `echo $ARTIFACTORY_DB_USERNAME` %>
      password: <%= `echo $ARTIFACTORY_DB_PASSWORD` %>
    nfs:
      server_ip: 10.60.4.56

