---
name: concourse

# replace with bosh status --uuid
director_uuid: <%= `bundle exec bosh status --uuid` %>

# pick a sane db name and password
atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: admin
  password: password

# replace all addresses with your VPC range
#
# e.g. X.X.0.2 -> 10.0.0.2
networks:
  - name: concourse
    type: manual
    subnets:
    - range: 10.60.0.0/16
      gateway: 10.60.0.1
      dns: [10.60.0.10]
      cloud_properties: {name: 'VM Network'}
      reserved: [10.60.7.0 - 10.60.7.100, 10.60.6.0/24, 10.60.5.0/24, 10.60.4.0/24, 10.60.3.0/24, 10.60.2.0/24, 10.60.1.0/24, 10.60.0.2 - 10.60.0.255, 10.60.8.1 - 10.60.255.254]
      static:
          - 10.60.7.110

releases:
  - name: concourse
    version: 0.71.1
  - name: garden-linux
    version: 0.331.0

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
    networks:
      - name: concourse
        static_ips: [10.60.7.110]
    properties:
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: tsa}
      - {release: concourse, name: atc}
    networks: [{name: concourse}]
    properties:
      atc:
        development_mode: true
        postgresql:
          database: *atc-db-name
          role: *atc-db-role

      consul:
        agent:
          servers: {lan: [10.60.7.110]}

  - name: db
    instances: 1
    resource_pool: databases
    persistent_disk: 10240
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: postgresql}
    networks: [{name: concourse}]
    properties:
      postgresql:
        databases: [{name: *atc-db-name}]
        roles: [*atc-db-role]

      consul:
        agent:
          servers: {lan: [10.60.7.110]}

  - name: worker
    instances: 1
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        btrfs_store_size_mb: 102400

      consul:
        agent:
          servers: {lan: [10.60.7.110]}

resource_pools:
  - name: web
    network: concourse
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      cpu: 1
      ram: 4_096
      disk: 4_000

  - name: discovery
    network: concourse
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      cpu: 1
      ram: 4_096
      disk: 4_000

  - name: databases
    network: concourse
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      cpu: 1
      ram: 4_096
      disk: 4_000

  - name: workers
    network: concourse
    stemcell:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      cpu: 2
      ram: 8_096
      disk: 64_000

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    cpu: 2
    ram: 4_096
    disk: 30_000

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
